### ISSUE TITLE
Page load

### ISSUE THREAD

**Issue by johnberrydev** [jberry93/koffee#7]
Page load is really slow.  Check out the network tab of dev tools.  Something wrong with the semantic.css.

![capture](https://cloud.githubusercontent.com/assets/689577/9241483/014a2c78-4129-11e5-9731-87521a96d09b.PNG)

**Comment by jberry93** [comment]
Seems to be fixed yet it is slightly sluggish as a result of materialize, bootstrap, the icons, and pictures. Probably unavoidable
<img width="1280" alt="pageloadfix" src="https://cloud.githubusercontent.com/assets/5133505/9255632/8142c252-419f-11e5-8df6-f7a1d779a105.png">
